### ISSUE TITLE
Feature Request: Parameter to set limit for auto quality select

### ISSUE THREAD

**Issue by Noctunus** [simplymemes/crunchyroll-dl#10]
Most of the time 720p is more then enough for any Anime - only some exceptional detailed and beautifully painted ones are really worth the 1080p - but simply selecting 720p as a default parameter will eventually run into an error when the series is only available in 480p.

So a limiter parameter for the already present auto-select would be very nice to limit the max resolution to download to e.g. 720p but if this is not available automatically select 480p as a fallback.

**Comment by simplymemes** [comment]
Decided to tackle this one, as it was the most annoying for me as well...

1.2.1 will now select the next best quality available to what you initially selected. I feel like this more automatic approach is better than the manual one you offered.

Example: `crunchyroll-dl -i https://www.crunchyroll.com/bakemonogatari/episode-1-hitagi-crab-part-1-610921 -u username -p password`
Since it's only in 480p, before it would never be able to download... Now it will automatically select 480p.

**Comment by Noctunus** [comment]
Verified from my side. Tested with -q 720p + whole series and got the output "Downloading in 480p, as 720p was not available."

Thanks a lot!
